# Generated by Django 6.0.2 on 2026-03-04 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=200)),
                ('clase_color', models.CharField(max_length=50)),
                ('imagen', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('nombre', models.CharField(max_length=60)),
                ('nombre_completo', models.CharField(max_length=120)),
                ('posicion', models.CharField(choices=[('Armador', 'Armador'), ('Receptor/Atacante', 'Receptor/Atacante'), ('Central', 'Central'), ('Opuesto', 'Opuesto'), ('Líbero', 'Líbero')], max_length=30)),
                ('edad', models.PositiveSmallIntegerField()),
                ('altura_cm', models.PositiveSmallIntegerField()),
                ('peso_kg', models.PositiveSmallIntegerField()),
                ('foto', models.CharField(max_length=100)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='equipos.equipo')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'ordering': ['equipo', 'orden'],
            },
        ),
    ]
