# Generated by Django 6.0.2 on 2026-03-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='hobby',
            field=models.CharField(default='', max_length=120),
        ),
    ]
